#!/usr/bin/env python
"""Generate the frontend's test fixtures from the real API.

A hand-written fixture is a statement about what the frontend believes the backend sends,
and it stays true right up until it silently stops being true. These are produced by
driving the actual FastAPI app against the same mocked Atlas transport the Python tests
use, and emitted as a typed TypeScript module.

That typing is the point. Because the generated file annotates each fixture as
``WorkflowState`` or ``Catalog``, ``tsc`` checks the real projection against the frontend's
declared contract. Rename a field in ``server/views.py`` without updating
``web/src/lib/types.ts`` and the frontend build fails, which is the failure mode you want -
rather than a panel quietly rendering ``undefined`` in production.

Run after changing any projection:

    uv run python scripts/generate_web_fixtures.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fastapi.testclient import TestClient  # noqa: E402

from api.client import AtlasClient  # noqa: E402
from core.config import Settings  # noqa: E402
from orchestration.pipeline import AnalysisPipeline  # noqa: E402
from server.app import app, get_pipeline_factory, request_settings  # noqa: E402
from tests.conftest import default_builder, make_transport  # noqa: E402

OUTPUT = ROOT / "web" / "src" / "test" / "fixtures.generated.ts"

SETTINGS = Settings(
    atlas_token="fixture-token",
    atlas_base_url="https://api.statebook.test",
    timeout_seconds=5.0,
    max_retries=1,
    openai_api_key=None,
    llm_model="none",
    log_level="WARNING",
)

# Two regions keeps the fixture readable. The panels do not care how many there are.
REGIONS = ["city:burlington-vt", "city:winooski-vt"]
OBJECTIVE = (
    "Compare Burlington and Winooski for a suburban apparel store targeting "
    "middle-income families. Prioritize growth and accessibility."
)

HEADER = '''/**
 * Generated by `scripts/generate_web_fixtures.py`. Do not edit by hand.
 *
 * These are real responses from the FastAPI app, captured against the mocked Atlas
 * transport. The type annotations below are a contract check: if a projection in
 * `server/views.py` changes shape and `src/lib/types.ts` is not updated to match, this
 * file stops compiling.
 */

import type { Catalog, SensitivityReport, WorkflowState } from "@/lib/types";
'''


def literal(value: object) -> str:
    """Render as a TypeScript literal. JSON is valid TS for these shapes.

    Emitted compactly. Pretty-printing triples the file for a machine-written artifact
    nobody reads line by line, and one fixture per line still gives a diff that says
    which fixture moved.
    """
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


def main() -> None:
    def factory(settings: Settings) -> AnalysisPipeline:
        return AnalysisPipeline(
            settings=SETTINGS,
            client_factory=lambda: AtlasClient(
                SETTINGS, transport=make_transport(default_builder())
            ),
        )

    app.dependency_overrides[get_pipeline_factory] = lambda: factory
    app.dependency_overrides[request_settings] = lambda: SETTINGS

    try:
        with TestClient(app) as client:
            catalog = client.get("/api/catalog").json()

            session = client.post("/api/sessions").json()["session_id"]

            review = client.post(
                f"/api/sessions/{session}/describe",
                json={
                    "objective": OBJECTIVE,
                    "geographies": REGIONS,
                    "use_llm": False,
                },
            ).json()

            clarify_session = client.post("/api/sessions").json()["session_id"]
            clarify = client.post(
                f"/api/sessions/{clarify_session}/describe",
                json={
                    "objective": "Where should we put our next store?",
                    "geographies": [],
                    "use_llm": False,
                },
            ).json()

            refused_session = client.post("/api/sessions").json()["session_id"]
            refused = client.post(
                f"/api/sessions/{refused_session}/describe",
                json={
                    "objective": (
                        "Which of these locations will generate the highest "
                        "five-year ROI?"
                    ),
                    "geographies": REGIONS,
                    "use_llm": False,
                },
            ).json()

            executed = client.post(
                f"/api/sessions/{session}/approve",
                json={"use_llm_narrative": False},
            ).json()

            sensitivity = client.get(f"/api/sessions/{session}/sensitivity").json()

            client.post(
                f"/api/sessions/{session}/assistant",
                json={"message": "Double the importance of household income"},
            )
            with_revision = client.get(f"/api/sessions/{session}").json()["state"]
    finally:
        app.dependency_overrides.clear()

    body = "\n".join(
        [
            HEADER,
            f"export const catalogFixture: Catalog = {literal(catalog)};\n",
            f"export const reviewStateFixture: WorkflowState = {literal(review)};\n",
            f"export const clarifyStateFixture: WorkflowState = {literal(clarify)};\n",
            f"export const refusedStateFixture: WorkflowState = {literal(refused)};\n",
            f"export const executedStateFixture: WorkflowState = {literal(executed)};\n",
            (
                "export const pendingRevisionStateFixture: WorkflowState = "
                f"{literal(with_revision)};\n"
            ),
            (
                "export const sensitivityFixture: SensitivityReport = "
                f"{literal(sensitivity)};\n"
            ),
        ]
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(body, encoding="utf-8")

    size_kb = OUTPUT.stat().st_size / 1024
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({size_kb:.0f} KB)")
    print(f"  review stage:   {review['stage']}")
    print(f"  clarify stage:  {clarify['stage']}")
    print(f"  refused stage:  {refused['stage']}")
    print(f"  executed stage: {executed['stage']}, {len(executed['versions'])} version(s)")
    print(f"  pending revision: {with_revision['pending_revision'] is not None}")


if __name__ == "__main__":
    main()
