/**
 * Test harness.
 *
 * Components read the workflow through `useSession`, so the harness stubs `fetch` with a
 * routing table rather than mocking the context. That keeps the API client, the request
 * shapes, and the header handling inside the test boundary - the interesting bugs in a
 * client/server split live at the seam, not inside a component.
 */

import { render, type RenderResult } from "@testing-library/react";
import type { ReactElement } from "react";
import { vi } from "vitest";

import { SessionProvider } from "@/lib/session";
import type { WorkflowState } from "@/lib/types";

import { catalogFixture, executedStateFixture } from "./fixtures.generated";

export interface StubOptions {
  state?: WorkflowState;
  llmEnabled?: boolean;
  atlasTokenPresent?: boolean;
  /** Extra routes, matched by substring against the request path. */
  routes?: Record<string, unknown>;
}

export interface Stub {
  calls: { url: string; method: string; headers: Record<string, string>; body: unknown }[];
  /** Requests that carried an OpenAI key header, for asserting on credential handling. */
  keyedCalls: () => Stub["calls"];
}

export function stubApi(options: StubOptions = {}): Stub {
  const state = options.state ?? executedStateFixture;
  const calls: Stub["calls"] = [];

  const routes: Record<string, unknown> = {
    "/api/health": {
      status: "ok",
      settings: {
        atlas_token_present: options.atlasTokenPresent ?? true,
        is_demo_token: true,
        atlas_base_url: "https://api.statebook.test",
        llm_enabled: options.llmEnabled ?? false,
        llm_model: "gpt-5.6-luna",
        llm_key_from_environment: false,
        default_llm_model: "gpt-5.6-luna",
      },
      demo_token_scope_note: catalogFixture.demo_token_scope_note,
    },
    "/api/catalog": catalogFixture,
    "/api/sessions": { session_id: "test-session", state },
    "/api/sessions/test-session/assistant": {
      messages: [],
      context: {
        suggestions: ["Why did the leading region come out on top?"],
        has_result: true,
        region_names: [],
        fact_count: 12,
      },
      llm_enabled: options.llmEnabled ?? false,
    },
    "/api/market-discovery/artifact": {
      artifact_version: "v1",
      feature_set_version: "acs5_2022_apparel_v1",
      model_version: "kmeans_zscore_v1",
      seed: 42,
      config_hash: "test",
      k: 5,
      min_population: 50000,
      n_counties_fit: 39,
      n_counties_total: 41,
      data_class: {
        data_class: "public_market_data",
        label: "Public market data",
        short_note: "Public government or licensed open data, not Atlas.",
      },
      quality: {
        k: 5,
        inertia: 1,
        silhouette: 0.3,
        selection_rule: "test",
        candidate_scores: { "5": 0.3 },
      },
      provenance_notes: ["Test fixture."],
      feature_ids: ["median_household_income"],
      dropped_correlated: [],
      features: [],
    },
    "/api/market-discovery/clusters": {
      clusters: [
        {
          cluster_id: "A01",
          label: "Archetype 01",
          member_count: 8,
          centroid_features: { median_household_income: 90000 },
          distinctive_high: ["median_household_income"],
          distinctive_low: [],
          data_class: {
            data_class: "public_market_data",
            label: "Public market data",
            short_note: "Public government or licensed open data, not Atlas.",
          },
        },
      ],
      artifact: {
        artifact_version: "v1",
        feature_set_version: "acs5_2022_apparel_v1",
        model_version: "kmeans_zscore_v1",
        seed: 42,
        config_hash: "test",
        k: 5,
        min_population: 50000,
        n_counties_fit: 39,
        n_counties_total: 41,
        data_class: {
          data_class: "public_market_data",
          label: "Public market data",
          short_note: "Public government or licensed open data, not Atlas.",
        },
        quality: {
          k: 5,
          inertia: 1,
          silhouette: 0.3,
          selection_rule: "test",
          candidate_scores: { "5": 0.3 },
        },
        provenance_notes: ["Test fixture."],
        feature_ids: ["median_household_income"],
        dropped_correlated: [],
        features: [],
      },
    },
    "/api/market-discovery/markets": { markets: [], artifact: {} },
    "/api/market-discovery/pca": { points: [], artifact: {} },
    "/api/retailer-simulation/meta": {
      simulator_version: "northstar_v1",
      brand: "NorthStar Apparel",
      benchmark_version: "v1",
      data_class: {
        data_class: "simulated_retailer_data",
        label: "Simulated",
        short_note: "Generated by a seeded simulator. Not observed retailer performance.",
      },
      provenance_notes: ["Fictional brand for demo."],
    },
    "/api/retailer-simulation/benchmarks": {
      version: "v1",
      brand: "NorthStar Apparel",
      provenance_notes: ["Test fixture."],
      active_count: 4,
      disabled_count: 2,
      data_class: {
        data_class: "public_company_benchmark",
        label: "Public company benchmark",
        short_note: "Aggregate figure from a public filing or official company site.",
      },
      benchmarks: [
        {
          metric: "avg_annual_store_sales_usd",
          value: 4200000,
          unit: "USD",
          source_name: "Illustrative aggregate",
          source_url: null,
          source_period: "FY2023",
          verification_state: "VERIFIED",
          usage: "Anchor per-store sales",
          data_class: {
            data_class: "public_company_benchmark",
            label: "Public company benchmark",
            short_note: "Aggregate figure from a public filing or official company site.",
          },
        },
        {
          metric: "ecommerce_share_pct",
          value: 28,
          unit: "percent",
          source_name: "Disabled placeholder",
          source_url: null,
          source_period: null,
          verification_state: "UNVERIFIED_DISABLED",
          usage: "Not used",
          data_class: {
            data_class: "public_company_benchmark",
            label: "Public company benchmark",
            short_note: "Aggregate figure from a public filing or official company site.",
          },
        },
      ],
    },
    "/api/retailer-simulation/defaults": {
      scenario: {
        store_count: 48,
        format_mix: { mall: 0.35, strip: 0.4, outlet: 0.25 },
        seed: 42,
        sales_target_usd: 200000000,
        margin_min_pct: 34,
        margin_max_pct: 42,
        data_class: {
          data_class: "user_assumption",
          label: "User assumption",
          short_note: "Stated by the user; not measured.",
        },
      },
    },
    ...options.routes,
  };

  const simulationFixture = {
    brand: "NorthStar Apparel",
    simulator_version: "northstar_v1",
    seed: 42,
    scenario: {
      store_count: 48,
      format_mix: { mall: 0.35, strip: 0.4, outlet: 0.25 },
      seed: 42,
      sales_target_usd: 200000000,
      margin_min_pct: 34,
      margin_max_pct: 42,
      data_class: {
        data_class: "user_assumption",
        label: "User assumption",
        short_note: "Stated by the user; not measured.",
      },
    },
    stores: [
      {
        store_id: "NS-001",
        name: "NorthStar Burlington Mall",
        format: "mall",
        city: "Burlington",
        state: "VT",
        lat: 44.48,
        lon: -73.21,
        sq_ft: 8500,
        annual_sales_usd: 4166666.67,
        gross_margin_pct: 38.0,
        host_geoid: "50007",
        host_name: "Chittenden County, Vermont",
        host_cluster_id: "A03",
        data_class: {
          data_class: "simulated_retailer_data",
          label: "Simulated",
          short_note: "Generated by a seeded simulator. Not observed retailer performance.",
        },
      },
    ],
    similar_market_profile: {
      cluster_id: "A03",
      cluster_label: "Archetype 03",
      focus_market_name: "Chittenden County, Vermont",
      store_count: 1,
      median_annual_sales_usd: 4166666.67,
      iqr_annual_sales_usd: { q1: 4166666.67, q3: 4166666.67 },
      median_gross_margin_pct: 38.0,
      store_ids: ["NS-001"],
      note: "Demo profile of fictional NorthStar stores in the same public-market archetype.",
      data_class: {
        data_class: "simulated_retailer_data",
        label: "Simulated",
        short_note: "Generated by a seeded simulator. Not observed retailer performance.",
      },
    },
    monthly: [
      {
        month: 1,
        label: "Jan",
        total_sales_usd: 15333333.33,
        store_count: 48,
        data_class: {
          data_class: "simulated_retailer_data",
          label: "Simulated",
          short_note: "Generated by a seeded simulator. Not observed retailer performance.",
        },
      },
    ],
    segments: [
      {
        segment_id: "families",
        label: "Families",
        share_pct: 35,
        data_class: {
          data_class: "simulated_retailer_data",
          label: "Simulated",
          short_note: "Generated by a seeded simulator. Not observed retailer performance.",
        },
      },
    ],
    reconciliation: [
      {
        metric: "total_annual_sales_usd",
        target: 200000000,
        generated: 200000000,
        tolerance_pct: 0.01,
        passed: true,
        note: "Scaled to target",
        data_class: {
          data_class: "simulated_retailer_data",
          label: "Simulated",
          short_note: "Generated by a seeded simulator. Not observed retailer performance.",
        },
      },
    ],
    assumptions: ["Fictional brand NorthStar Apparel; not observed retailer performance."],
    provenance_notes: ["Test fixture."],
    data_class: {
      data_class: "simulated_retailer_data",
      label: "Simulated",
      short_note: "Generated by a seeded simulator. Not observed retailer performance.",
    },
    reconciliation_passed: true,
  };

  routes["/api/sessions/test-session/retailer-simulation/run"] = {
    simulation: simulationFixture,
  };
  routes["/api/sessions/test-session/retailer-simulation"] = {
    simulation: simulationFixture,
  };

  const analogSearchFixture = {
    candidate_market_id: "city:burlington-vt",
    candidate_geoid: "50007",
    candidate_name: "Chittenden County, Vermont",
    candidate_cluster_id: "A01",
    matches: [
      {
        store_id: "NS-001",
        store_name: "NorthStar Burlington Mall",
        format: "mall",
        host_geoid: "50007",
        host_name: "Chittenden County, Vermont",
        similarity: 0.82,
        distance: 0.22,
        contributions: [
          {
            feature_id: "median_household_income",
            display_name: "Median household income",
            candidate_value: 89400,
            store_value: 89400,
            weight: 1.3,
            signed_contribution: 0.01,
          },
        ],
        mismatches: [],
        performance_summary: {
          median_annual_sales_usd: 4166666.67,
          iqr_annual_sales_usd: [3800000, 4500000],
          median_gross_margin_pct: 38.0,
          iqr_gross_margin_pct: [36.0, 40.0],
          data_class: {
            data_class: "simulated_retailer_data",
            label: "Simulated",
            short_note: "Generated by a seeded simulator. Not observed retailer performance.",
          },
        },
        data_class: {
          data_class: "public_market_data",
          label: "Public market data",
          short_note: "Public government or licensed open data, not Atlas.",
        },
      },
    ],
    aggregate_range: {
      min_similarity: 0.82,
      max_similarity: 0.82,
      median_similarity: 0.82,
      data_class: {
        data_class: "public_market_data",
        label: "Public market data",
        short_note: "Public government or licensed open data, not Atlas.",
      },
    },
    analogy_strength: "strong",
    warnings: [],
    feature_ids: ["median_household_income"],
    matcher_version: "analog_v1",
    feature_set_version: "acs5_2022_apparel_v1",
    context_pack: [
      "Analog search for Chittenden County, Vermont (GEOID 50007) using NorthStar Apparel simulated stores.",
      "Matching uses public ACS county features only.",
    ],
    data_class: {
      data_class: "public_market_data",
      label: "Public market data",
      short_note: "Public government or licensed open data, not Atlas.",
    },
    data_class_notes: {
      candidate_profile: {
        data_class: "public_market_data",
        label: "Public market data",
        short_note: "Public government or licensed open data, not Atlas.",
      },
      match_features: {
        data_class: "public_market_data",
        label: "Public market data",
        short_note: "Public government or licensed open data, not Atlas.",
      },
      performance_summary: {
        data_class: "simulated_retailer_data",
        label: "Simulated",
        short_note: "Generated by a seeded simulator. Not observed retailer performance.",
      },
    },
  };

  routes["/api/analog-matching/meta"] = {
    matcher_version: "analog_v1",
    feature_set_version: "acs5_2022_apparel_v1",
    matching_features: [],
    thresholds: {
      min_strong_similarity: 0.72,
      min_moderate_similarity: 0.55,
      min_peer_count: 3,
      default_top_k: 5,
      max_top_k: 20,
    },
    data_class: {
      data_class: "public_market_data",
      label: "Public market data",
      short_note: "Public government or licensed open data, not Atlas.",
    },
    provenance_notes: ["Test fixture."],
  };
  routes["/api/sessions/test-session/analog-matching/search"] = {
    search: analogSearchFixture,
  };
  routes["/api/sessions/test-session/analog-matching"] = {
    search: analogSearchFixture,
  };

  vi.stubGlobal(
    "fetch",
    vi.fn(async (input: RequestInfo | URL, init?: RequestInit) => {
      const url = String(input);
      calls.push({
        url,
        method: init?.method ?? "GET",
        headers: (init?.headers ?? {}) as Record<string, string>,
        body: init?.body ? JSON.parse(String(init.body)) : undefined,
      });

      // Prefer a suffix or exact path match over a bare prefix. Otherwise the create
      // route `/api/sessions` steals every `/api/sessions/{id}/…` call, and an `/edit`
      // stub never fires.
      const path = new URL(url, "http://local.test").pathname;

      // Market profiles are `/markets/{id}` — do not let the list route swallow them.
      if (
        path.startsWith("/api/market-discovery/markets/") &&
        path !== "/api/market-discovery/markets/"
      ) {
        return new Response(
          JSON.stringify({
            detail: "No county archetype stub for this geography in tests.",
          }),
          { status: 404, headers: { "Content-Type": "application/json" } },
        );
      }

      const match =
        Object.keys(routes)
          .filter((route) => path === route || path.endsWith(route))
          .sort((a, b) => b.length - a.length)[0] ??
        Object.keys(routes)
          .filter((route) => path.includes(route))
          .sort((a, b) => b.length - a.length)[0];

      if (!match) {
        return new Response(JSON.stringify({ detail: `No stub for ${url}` }), {
          status: 404,
          headers: { "Content-Type": "application/json" },
        });
      }
      return new Response(JSON.stringify(routes[match]), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }),
  );

  return { calls, keyedCalls: () => calls.filter((call) => "X-OpenAI-Key" in call.headers) };
}

export function renderApp(ui: ReactElement): RenderResult {
  return render(<SessionProvider>{ui}</SessionProvider>);
}
