"""Data-class provenance.

Plan-field provenance (``user_supplied`` / ``planner_inferred`` / …) answers *who set a
value*. This enum answers a different question: *what kind of evidence is this number?*

Phases 2–4 introduce public market data and simulated retailer data alongside Atlas
evidence. Without an explicit class on every wire payload, a chart or narrative can silently
combine them. Keeping the class on the model - not only in UI copy - is what makes that
failure mode a schema error rather than a screenshot review.
"""

from __future__ import annotations

from enum import StrEnum


class DataClass(StrEnum):
    ATLAS_EVIDENCE = "atlas_evidence"
    PUBLIC_MARKET_DATA = "public_market_data"
    PUBLIC_COMPANY_BENCHMARK = "public_company_benchmark"
    SIMULATED_RETAILER_DATA = "simulated_retailer_data"
    USER_SUPPLIED_PROPRIETARY_DATA = "user_supplied_proprietary_data"
    USER_ASSUMPTION = "user_assumption"
    AGENT_INTERPRETATION = "agent_interpretation"


DATA_CLASS_LABELS: dict[DataClass, str] = {
    DataClass.ATLAS_EVIDENCE: "Atlas verified",
    DataClass.PUBLIC_MARKET_DATA: "Public market data",
    DataClass.PUBLIC_COMPANY_BENCHMARK: "Public company benchmark",
    DataClass.SIMULATED_RETAILER_DATA: "Simulated",
    DataClass.USER_SUPPLIED_PROPRIETARY_DATA: "Proprietary (user)",
    DataClass.USER_ASSUMPTION: "User assumption",
    DataClass.AGENT_INTERPRETATION: "Agent interpretation",
}

DATA_CLASS_SHORT_NOTES: dict[DataClass, str] = {
    DataClass.ATLAS_EVIDENCE: "Returned by the StateBook Atlas API and gated by the metric registry.",
    DataClass.PUBLIC_MARKET_DATA: "Public government or licensed open data, not Atlas.",
    DataClass.PUBLIC_COMPANY_BENCHMARK: "Aggregate figure from a public filing or official company site.",
    DataClass.SIMULATED_RETAILER_DATA: "Generated by a seeded simulator. Not observed retailer performance.",
    DataClass.USER_SUPPLIED_PROPRIETARY_DATA: "Reserved for future proprietary ingestion. Not active in this build.",
    DataClass.USER_ASSUMPTION: "Stated by the user; not measured.",
    DataClass.AGENT_INTERPRETATION: "Planner or assistant wording. Not a data value.",
}


def data_class_view(data_class: DataClass) -> dict[str, str]:
    return {
        "data_class": str(data_class),
        "label": DATA_CLASS_LABELS[data_class],
        "short_note": DATA_CLASS_SHORT_NOTES[data_class],
    }


__all__ = [
    "DATA_CLASS_LABELS",
    "DATA_CLASS_SHORT_NOTES",
    "DataClass",
    "data_class_view",
]
